CC := gcc
CC_FLAGS := -Wall -Wextra -Werror

SRCS := ft_printf_getdata.c ft_printf_isdata.c \
	ft_printf_misc.c ft_printf.c

OBJS := $(SRCS:%.c=%.o)

NAME := libprintf.a

$(NAME):

all:

clean:

fclean:

re: